# [Info]
site_name: Frankoxer 的小站
site_url: https://frankoxer.github.io/
site_description: Frankoxer 的个人网站

############################################################################################

# [UI]
## [top]
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png # 左上角的logo
  favicon: assets/images/logo.png
  font:
    text: Mukta
    code: Fira Code
  palette:
    - scheme: default # 日间模式
      primary: white # 上方的
      accent: brown # 链接等可交互元件的高亮色
      toggle:
        icon: material/toggle-switch-off-outline # 图标
        name: Switch to dark mode # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black
      accent: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    #- navigation.footer # 底部的翻页
    # - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/git-alt
edit_uri: edit/main/docs # 编辑按钮跳转的链接

## [top-right corner]
repo_url: https://github.com/Frankoxer/frankoxer.github.io # 右上角点击跳转的链接
repo_name: frankoxer.github.io # 右上角的名字

## [bottom-left corner]
copyright: Copyright © 2023-2024 Frankoxer # 左下角的版权声明

## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/85414704
      name: Bilibili | 五伏亿安 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/frankoxer
      name: GitHub | Frankoxer

############################################################################################

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags

markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition
  - pymdownx.details # admonition需要
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - tables
  - def_list
  - md_in_html
  - sane_lists
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols  #智能符号
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docourse/mkdocourse/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docourse/mkdocourse/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  # - mkdocourse/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  #- mkdocourse/css/no-footer.css # 不使用底部的翻页
  #- mkdocourse/css/unordered-list-symbols.css # multiplt unordered list symbols

############################################################################################

#[Navigation]
nav: 
  - 主页: index.md
  - 学习: 
    - study/index.md
    - 校内课程:
      - 程序设计与算法基础: study/course/fpa/final-exam-re.md
      - 数据结构基础:
        - study/course/ds/index.md
        - 算法分析基础: study/course/ds/ch1.md
        - 线性数据结构: study/course/ds/ch2.md
        - 树: study/course/ds/ch3.md
        - 图: study/course/ds/ch4.md
        - 排序: study/course/ds/ch5.md
        - 散列: study/course/ds/ch6.md
      - 高级数据结构与算法分析:
        - study/course/ads/index.md
        - AVL/Splay/摊还分析: study/course/ads/lec1.md
        - 红黑树/B+ 树: study/course/ads/lec2.md
        - 倒排索引: study/course/ads/lec3.md
        - 左式堆与斜堆: study/course/ads/lec4.md
        - 二项堆: study/course/ads/lec5.md
        - 回溯: study/course/ads/lec6.md
        - 分治法: study/course/ads/lec7.md
        - 动态规划: study/course/ads/lec8.md
        - 贪心算法: study/course/ads/lec9.md
        - NP: study/course/ads/lec10.md
        - 近似算法: study/course/ads/lec11.md
        - 局部搜索: study/course/ads/lec12.md
        - 随机算法: study/course/ads/lec13.md
      - 人工智能引论:
        - study/course/ai/index.md
    - 其他技能学习:
      - HTML 学习:
        - study/self/html/index.md
        - HTML 简介: study/self/html/lec1.md
        - 段落与基本格式: study/self/html/lec2.md
        - 其他格式: study/self/html/lec3.md
        - 其他元素: study/self/html/lec4.md
      - CSS 学习:
        - study/self/css/index.md
        - CSS 简介: study/self/css/lec1.md
        - 背景样式: study/self/css/lec2.md
  - 实践:
    - practice/index.md
    - C++ 项目管理与工程实践: practice/MyMUG.md
  - 关于:
    - about/index.md