# [Info]
site_name: 5V1A的个人主页
site_url: https://frank-prince.github.io/

#[Navigation]
nav: 
  - CS: 
    - CS/index.md
    - 编程语言: 
      - C/C++: 
        - 程算期末Cheating Sheet: CS/Language/C/final-exam-re.md


# [UI]
## [top]
theme:
  name: material
  font:
    text: Noto Sans Simplified Chinese
    code: JetBrains Mono
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/frank-prince/frank-prince.github.io # 右上角点击跳转的链接
repo_name: frank-prince.github.io # 右上角的名字
## [bottom-left corner]
copyright: 5V1A # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/85414704
      name: Bilibili | 五伏亿安 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/frank-prince
      name: GitHub | frank-prince
